[project]
name = "rubi-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shahzeel", email = "shahzeelahmadbrand@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.3",
    "edge-tts>=7.2.8",
    "fastapi>=0.115.0",
    "faster-whisper>=1.2.1",
    "groq>=1.7.0",
    "httpx[socks]>=0.28.1",
    "numpy>=2.4.6",
    "openai>=3.23.0",
    "openwakeword>=0.6.0",
    "piper-tts>=1.8.0",
    "pynput>=1.8.2",
    "python-dotenv>=1.2.4",
    "python-telegram-bot>=22.8",
    "sounddevice>=0.5.6",
    "streamlit>=1.40.0",
    "uvicorn[standard]>=0.30.0",
]

[project.scripts]
rubi-assistant = "rubi_assistant:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
